services:

  keycloak-1:
    image: quay.io/keycloak/keycloak:25.0.2
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command:
      - start-dev
      - --import-realm

#  keycloak-2:
#    image: quay.io/keycloak/keycloak:25.0.2
#    ports:
#      - "8082:8080"
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    volumes:
#      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
#    command:
#      - start-dev
#      - --import-realm
